import type { AnalysisResult } from "../types/analysis";

interface Props {
  requirementText: string;
  reqType: string;
  priority: string;
  result: AnalysisResult;
}

const TYPE_LABEL: Record<string, string> = {
  functional:     "Functional",
  non_functional: "Non-Functional",
  constraint:     "Constraint",
};

const PRIORITY_LABEL: Record<string, string> = {
  must:   "Must Have",
  should: "Should Have",
  could:  "Could Have",
  wont:   "Won't Have",
};

function buildSRS(
  text: string,
  reqType: string,
  priority: string,
  result: AnalysisResult,
): string {
  const now = new Date().toISOString().split("T")[0];
  const sep = "=".repeat(60);

  const findings = result.findings.length > 0
    ? result.findings
        .map((f) => `  [${f.severity.toUpperCase()}] ${f.rule_id}: ${f.message}`)
        .join("\n")
    : "  No issues detected.";

  const suggestions = result.suggestions.length > 0
    ? result.suggestions.map((s) => `  - ${s}`).join("\n")
    : "  No AI suggestions generated.";

  return `SOFTWARE REQUIREMENTS SPECIFICATION (Simplified)
Generated by ReqCheck — ${now}
${sep}

REQUIREMENT
-----------
${text}

CLASSIFICATION
--------------
Type:     ${TYPE_LABEL[reqType]  ?? reqType}
Priority: ${PRIORITY_LABEL[priority] ?? priority} (MoSCoW)

QUALITY INDICATORS
------------------
Clarity Score:     ${result.clarity_score} / 100
Testability Score: ${result.testability_score} / 100

FINDINGS
--------
${findings}

AI SUGGESTIONS
--------------
${result.rag_error ? `  Unavailable: ${result.rag_error}` : suggestions}

${sep}
Note: This is a simplified SRS excerpt for writing support purposes.
It does not constitute a formal requirements specification document.
`;
}

export default function ExportButton({ requirementText, reqType, priority, result }: Props) {
  function handleExport() {
    const content = buildSRS(requirementText, reqType, priority, result);
    const blob    = new Blob([content], { type: "text/plain" });
    const url     = URL.createObjectURL(blob);
    const link    = document.createElement("a");
    link.href     = url;
    link.download = `reqcheck-export-${Date.now()}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  }

  return (
    <button
      onClick={handleExport}
      style={{
        marginTop: "16px",
        padding: "8px 18px",
        background: "#374151",
        color: "#fff",
        border: "none",
        borderRadius: "4px",
        cursor: "pointer",
        fontWeight: 600,
        fontSize: "0.85rem",
      }}
    >
      &#8659; Export SRS
    </button>
  );
}
